# name: Node.js CD

# on:
#   workflow_run:
#     workflows: ["Node.js CI"]
#     branches: [main, develop]
#     types:
#       - completed

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
#     steps:

      
#     - uses: actions/checkout@v4
#       with:
#         fetch-depth: 0
#     - name: Install Heroku CLI
#       run: |
#         curl https://cli-assets.heroku.com/install.sh | sh
#     - name: Git config
#       run: |
#         git config --global user.email "${{ github.actor }}@users.noreply.github.com"
#         git config --global user.name "${{ github.actor }}"
#     - name: Set environment variables
#       id: vars
#       run: |
#         if [[ ${{ github.event.workflow_run.head_branch }} == 'main' ]]; then
#           echo "ENV=production" >> $GITHUB_ENV
#           echo "APP_NAME=${{ secrets.HEROKU_PROD_APP_NAME }}" >> $GITHUB_ENV
#         elif [[ ${{ github.event.workflow_run.head_branch }} == 'develop' ]]; then
#           echo "ENV=staging" >> $GITHUB_ENV
#           echo "APP_NAME=${{ secrets.HEROKU_STAGING_APP_NAME }}" >> $GITHUB_ENV
#         fi
#     - name: Deploy to Heroku
#       uses: akhileshns/heroku-deploy@v3.12.13
#       with:
#         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#         heroku_app_name: ${{ env.APP_NAME }}
#         heroku_email: ${{ github.actor }}@users.noreply.github.com
#         env_file: ".env.${{ env.ENV }}"
#         justlogin: true