name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Hello World
        run: echo "Hello, GitHub Actions!"
      
      - name: Current time
        run: echo "Current time is $(date)"